# Generated by Django 2.0.1 on 2018-01-30 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseDepartment', models.CharField(max_length=3)),
                ('courseNumber', models.CharField(max_length=3)),
                ('courseName', models.CharField(max_length=50)),
                ('averageRating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('numberOfRatings', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('courseDepartment', models.CharField(max_length=3)),
                ('courseNumber', models.CharField(max_length=3)),
                ('reviewId', models.AutoField(primary_key=True, serialize=False)),
                ('reviewerId', models.IntegerField()),
                ('review', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('reviewDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='GradePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseDepartment', models.CharField(max_length=3)),
                ('courseNumber', models.CharField(max_length=3)),
                ('fallSem15', models.DecimalField(decimal_places=1, max_digits=3)),
                ('springSem15', models.DecimalField(decimal_places=1, max_digits=3)),
                ('fallSem16', models.DecimalField(decimal_places=1, max_digits=3)),
                ('springSem16', models.DecimalField(decimal_places=1, max_digits=3)),
                ('fallSem17', models.DecimalField(decimal_places=1, max_digits=3)),
                ('springSem17', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('instructorId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='gradepoint',
            unique_together={('courseDepartment', 'courseNumber')},
        ),
        migrations.AddField(
            model_name='coursereview',
            name='instructorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Instructor'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('courseDepartment', 'courseNumber')},
        ),
    ]
