# Generated by Django 2.0 on 2018-01-03 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseId', models.AutoField(primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=50)),
                ('courseNumber', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('reviewId', models.AutoField(primary_key=True, serialize=False)),
                ('review', models.CharField(max_length=50)),
                ('review_date', models.DateField()),
                ('professor', models.CharField(max_length=50)),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
            ],
        ),
    ]
