# Generated by Django 2.0 on 2018-01-28 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursereview',
            name='instructorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Instructor'),
        ),
    ]
